import { useState, useRef } from "react";
import Head from "next/head";

import { AiFillEye, AiFillEyeInvisible, AiOutlineUser } from "react-icons/ai";

import { Form } from "@unform/web";

import styles from "../styles/Home.module.scss";

import { Input } from "../components/InputComponent";

export default function Home() {
  const formRef = useRef();
  const [inputType, setInputType] = useState("password");

  function handleTypeInputText() {
    setInputType("text");
  }
  function handleTypeInputPassword() {
    setInputType("password");
  }

  async function handleSubmit(data, { reset }) {
    console.log(data);

    reset();
  }
  return (
    <div className={styles.ContainerContent}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.ContainertForm}>
        <div className={styles.classNameTopSvgUSer}>
          <AiOutlineUser />
        </div>
        <h2>Login</h2>
        <main>
          <Form ref={formRef} onSubmit={handleSubmit}>
            <Input name="user.email" type="text" placeholder="email" />
            <div>
              <Input
                name="user.password"
                type={inputType}
                placeholder="password"
              />
              {inputType === "password" ? (
                <AiFillEye onClick={handleTypeInputText} />
              ) : (
                <AiFillEyeInvisible onClick={handleTypeInputPassword} />
              )}
            </div>
            <div>
              <button type="submit">Submit</button>
            </div>
          </Form>
        </main>
      </div>
    </div>
  );
}
